all: clear part1 part2 part3
clear:
	clear
part1:
	@gcc part1.c -o test1
	@./test1
	@rm -f test1
part2:
	@gcc part2.c -lm -o test2
	@./test2
	@rm -f test2
part3:
	@gcc part3.c -o test3
	@./test3
	@rm -f test3
